#macro	UP		0
#macro	DOWN	1
#macro	LEFT	2
#macro	RIGHT	3
#macro	SELECT	4
#macro	START	5
#macro	SHOOT	6
#macro	JUMP	7

#macro BBOX_BOTTOM	0
#macro BBOX_TOP		1
#macro BBOX_LEFT	2
#macro BBOX_RIGHT	3

#macro IDLE			0
#macro SKATING		1
#macro CROUCHING	2
#macro JUMPING		3
#macro SLAMMING		4
#macro RECOVERING	5
#macro HIT			6
#macro CLIMBING		7

#macro HOT_SPOT_X				0
#macro HOT_SPOT_Y				1
#macro RIGHT_EDGE_X				2
#macro RIGHT_EDGE_Y				3
#macro LEFT_EDGE_X				4
#macro LEFT_EDGE_Y				5
#macro BOTTOM_RIGHT_X			6
#macro BOTTOM_RIGHT_Y			7
#macro BOTTOM_LEFT_X			8
#macro BOTTOM_LEFT_Y			9
#macro SLOPE_CATCHER_LEFT_X		10
#macro SLOPE_CATCHER_LEFT_Y		11
#macro SLOPE_CATCHER_RIGHT_X	12
#macro SLOPE_CATCHER_RIGHT_Y	13
#macro TOP_X					14
#macro TOP_Y					15
